# Generated by Django 2.0.7 on 2018-07-13 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caballos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7)),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cerdos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7)),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ferias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feria', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Lanares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7)),
                ('cantidad', models.IntegerField()),
                ('ciudad_feria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Ciudades')),
            ],
        ),
        migrations.CreateModel(
            name='NovillosEngorda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7)),
                ('cantidad', models.IntegerField()),
                ('ciudad_feria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Ciudades')),
            ],
        ),
        migrations.CreateModel(
            name='NovillosGordo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7)),
                ('cantidad', models.IntegerField()),
                ('ciudad_feria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Ciudades')),
            ],
        ),
        migrations.CreateModel(
            name='Terneras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7)),
                ('cantidad', models.IntegerField()),
                ('ciudad_feria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Ciudades')),
            ],
        ),
        migrations.CreateModel(
            name='Terneros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7)),
                ('cantidad', models.IntegerField()),
                ('ciudad_feria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Ciudades')),
            ],
        ),
        migrations.CreateModel(
            name='Toros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7)),
                ('cantidad', models.IntegerField()),
                ('ciudad_feria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Ciudades')),
            ],
        ),
        migrations.CreateModel(
            name='VacasEngorda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7)),
                ('cantidad', models.IntegerField()),
                ('ciudad_feria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Ciudades')),
            ],
        ),
        migrations.CreateModel(
            name='VacasGorda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7)),
                ('cantidad', models.IntegerField()),
                ('ciudad_feria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Ciudades')),
            ],
        ),
        migrations.CreateModel(
            name='VaquillasEngorda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7)),
                ('cantidad', models.IntegerField()),
                ('ciudad_feria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Ciudades')),
            ],
        ),
        migrations.CreateModel(
            name='VaquillasGorda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7)),
                ('cantidad', models.IntegerField()),
                ('ciudad_feria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Ciudades')),
            ],
        ),
        migrations.AddField(
            model_name='ciudades',
            name='ferias',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Ferias'),
        ),
        migrations.AddField(
            model_name='cerdos',
            name='ciudad_feria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Ciudades'),
        ),
        migrations.AddField(
            model_name='caballos',
            name='ciudad_feria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Ciudades'),
        ),
    ]
