# Generated by Django 2.0.7 on 2018-07-25 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caballos',
            name='precio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cerdos',
            name='precio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='lanares',
            name='precio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='novillosengorda',
            name='precio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='novillosgordo',
            name='precio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='terneras',
            name='precio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='terneros',
            name='precio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='toros',
            name='precio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='vacasengorda',
            name='precio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='vacasgorda',
            name='precio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='vaquillasengorda',
            name='precio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='vaquillasgorda',
            name='precio',
            field=models.FloatField(),
        ),
    ]
